[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_snapshot = "En9fSSnkmcgHoKx4wBjRf8RbGvL352f5zFfDu32UPN3m"

[programs.devnet]
spl_snapshot = "En9fSSnkmcgHoKx4wBjRf8RbGvL352f5zFfDu32UPN3m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "../keys/program.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
